# permissions for end users to view keydbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keydb-viewer-role
rules:
- apiGroups:
  - cache.github.com
  resources:
  - keydbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.github.com
  resources:
  - keydbs/status
  verbs:
  - get
